package com.anarky.showtrack.core.network.auth

import java.util.Base64
import javax.crypto.Cipher
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject
import javax.inject.Singleton

/**
 * AES-256/GCM over a key supplied by a [SecretKeySource].
 *
 * GCM is authenticated encryption, so a tampered or truncated ciphertext fails to decrypt rather
 * than yielding garbage — which is what makes [decrypt] returning null a safe "treat the user as
 * logged out" signal instead of a guess.
 *
 * The IV is generated by the provider per encryption (never reused, which is the one way to
 * destroy GCM) and prepended to the ciphertext, because it is needed to decrypt and is not a
 * secret.
 *
 * `java.util.Base64`, not `android.util.Base64`: identical output, but the Android one is a stub
 * that throws in a JVM unit test — and every bug this class can have (a wrong IV length, a
 * padding or line-wrap mismatch between encode and decode) is precisely the kind that only a
 * round-trip test catches. minSdk is 29, well past `java.util.Base64`'s API 26.
 */
@Singleton
class TokenCrypto
    @Inject
    constructor(
        private val keys: SecretKeySource,
    ) {
        fun encrypt(plaintext: String): String {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.ENCRYPT_MODE, keys.key())
            val iv = cipher.iv
            check(iv.size == IV_LENGTH) { "expected a $IV_LENGTH-byte GCM IV, got ${iv.size}" }
            val ciphertext = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))
            return Base64.getEncoder().encodeToString(iv + ciphertext)
        }

        /** Null when the stored value cannot be authenticated — a rotated or invalidated key, or tampering. */
        @Suppress("TooGenericExceptionCaught", "SwallowedException")
        fun decrypt(encoded: String): String? {
            return try {
                val bytes = Base64.getDecoder().decode(encoded)
                if (bytes.size <= IV_LENGTH) return null
                val cipher = Cipher.getInstance(TRANSFORMATION)
                cipher.init(
                    Cipher.DECRYPT_MODE,
                    keys.key(),
                    GCMParameterSpec(TAG_LENGTH_BITS, bytes, 0, IV_LENGTH),
                )
                String(cipher.doFinal(bytes, IV_LENGTH, bytes.size - IV_LENGTH), Charsets.UTF_8)
            } catch (e: Exception) {
                // Total on purpose: every failure mode here (GeneralSecurityException, the
                // KeyStore's own runtime exceptions, a malformed Base64 string) means the same
                // thing to the caller — there is no usable token. Narrowing the catch would let
                // one of them crash the app on a corrupted store instead of logging the user out.
                null
            }
        }

        internal companion object {
            const val KEY_SIZE_BITS = 256
            private const val TRANSFORMATION = "AES/GCM/NoPadding"
            private const val TAG_LENGTH_BITS = 128
            private const val IV_LENGTH = 12
        }
    }
