package com.anarky.showtrack.core.network.auth

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject
import javax.inject.Singleton

/**
 * AES-256/GCM against a key that never leaves the Android Keystore (decision A-I).
 *
 * `EncryptedSharedPreferences` is deprecated and deliberately not used. GCM is authenticated
 * encryption, so a tampered ciphertext fails to decrypt rather than yielding garbage — which is
 * what makes [decrypt] returning null a safe "treat the user as logged out" signal.
 *
 * The IV is generated by the Keystore provider per encryption (never reused, which is the one
 * way to destroy GCM) and prepended to the ciphertext, because it is needed to decrypt and is
 * not a secret.
 */
@Singleton
class TokenCrypto
    @Inject
    constructor() {
        fun encrypt(plaintext: String): String {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.ENCRYPT_MODE, key())
            val iv = cipher.iv
            val ciphertext = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))
            return Base64.encodeToString(iv + ciphertext, Base64.NO_WRAP)
        }

        /** Null when the stored value cannot be authenticated — a rotated or invalidated key, or tampering. */
        @Suppress("TooGenericExceptionCaught", "SwallowedException")
        fun decrypt(encoded: String): String? {
            return try {
                val bytes = Base64.decode(encoded, Base64.NO_WRAP)
                if (bytes.size <= IV_LENGTH) return null
                val cipher = Cipher.getInstance(TRANSFORMATION)
                cipher.init(
                    Cipher.DECRYPT_MODE,
                    key(),
                    GCMParameterSpec(TAG_LENGTH_BITS, bytes, 0, IV_LENGTH),
                )
                String(cipher.doFinal(bytes, IV_LENGTH, bytes.size - IV_LENGTH), Charsets.UTF_8)
            } catch (e: Exception) {
                // Total on purpose: every failure mode here (GeneralSecurityException, the
                // KeyStore's own runtime exceptions, a malformed Base64 string) means the same
                // thing to the caller — there is no usable token. Narrowing the catch would let
                // one of them crash the app on a corrupted store instead of logging the user out.
                null
            }
        }

        private fun key(): SecretKey {
            val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
            (keyStore.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

            val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
            generator.init(
                KeyGenParameterSpec
                    .Builder(KEY_ALIAS, KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT)
                    .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                    .setKeySize(KEY_SIZE_BITS)
                    // No setUserAuthenticationRequired: a background token refresh must work with
                    // the screen locked, and requiring auth here would fail every one of them.
                    .build(),
            )
            return generator.generateKey()
        }

        private companion object {
            const val ANDROID_KEYSTORE = "AndroidKeyStore"
            const val KEY_ALIAS = "showtrack.tokens"
            const val TRANSFORMATION = "AES/GCM/NoPadding"
            const val KEY_SIZE_BITS = 256
            const val TAG_LENGTH_BITS = 128
            const val IV_LENGTH = 12
        }
    }
