"""create media

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-12 10:15:14.644117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('type', sa.Enum('anime', 'tv', name='type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('source', sa.Enum('anilist', 'tmdb', name='source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('genres', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('next_episode_season', sa.Integer(), nullable=True),
    sa.Column('next_episode_number', sa.Integer(), nullable=True),
    sa.Column('next_episode_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('airing', 'finished', 'not_yet_aired', name='status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media')),
    sa.UniqueConstraint('source', 'external_id', name=op.f('uq_media_source_external_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    # ### end Alembic commands ###
