"""create user_media

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-12 14:02:14.934658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_media',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('watching', 'completed', 'dropped', 'planned', 'paused', name='status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('progress', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('favorite', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score IS NULL OR (score >= 1.0 AND score <= 10.0)', name=op.f('ck_user_media_score_range')),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_user_media_media_id_media'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_media_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_media')),
    sa.UniqueConstraint('user_id', 'media_id', name=op.f('uq_user_media_user_id_media_id'))
    )
    op.create_index(op.f('ix_user_media_media_id'), 'user_media', ['media_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_media_media_id'), table_name='user_media')
    op.drop_table('user_media')
    # ### end Alembic commands ###
