"""create recommendation tables

Revision ID: 0012
Revises: 0011
Create Date: 2026-08-24 11:29:58.793634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0012'
down_revision: Union[str, Sequence[str], None] = '0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_similarity',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_media_id', sa.Uuid(), nullable=False),
    sa.Column('similar_media_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    # BARE "not_self", not "ck_media_similarity_not_self": a named CheckConstraint attached
    # inside op.create_table is subject to the same naming-convention re-application as
    # op.drop_constraint/op.create_check_constraint — the qualified form renders as
    # `ck_media_similarity_ck_media_similarity_not_self`. Same trap 0009 and 0011 documented.
    sa.CheckConstraint('source_media_id <> similar_media_id', name='not_self'),
    sa.ForeignKeyConstraint(['similar_media_id'], ['media.id'], name=op.f('fk_media_similarity_similar_media_id_media'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_media_id'], ['media.id'], name=op.f('fk_media_similarity_source_media_id_media'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_similarity')),
    sa.UniqueConstraint('source_media_id', 'similar_media_id', name=op.f('uq_media_similarity_source_media_id_similar_media_id'))
    )
    op.create_index(op.f('ix_media_similarity_similar_media_id'), 'media_similarity', ['similar_media_id'], unique=False)
    op.create_table('recommendation',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('seed_media_id', sa.Uuid(), nullable=False),
    sa.Column('matched_genres', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_recommendation_media_id_media'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seed_media_id'], ['media.id'], name=op.f('fk_recommendation_seed_media_id_media'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendation_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation')),
    sa.UniqueConstraint('user_id', 'media_id', name=op.f('uq_recommendation_user_id_media_id')),
    sa.UniqueConstraint('user_id', 'rank', name=op.f('uq_recommendation_user_id_rank'))
    )
    op.create_index(op.f('ix_recommendation_media_id'), 'recommendation', ['media_id'], unique=False)
    op.create_table('recommendation_run',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_entry_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendation_run_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_recommendation_run'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_run')
    op.drop_index(op.f('ix_recommendation_media_id'), table_name='recommendation')
    op.drop_table('recommendation')
    op.drop_index(op.f('ix_media_similarity_similar_media_id'), table_name='media_similarity')
    op.drop_table('media_similarity')
    # ### end Alembic commands ###
