"""create social tables

Revision ID: 0014
Revises: 0013
Create Date: 2026-08-25 14:28:52.753232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0014'
down_revision: Union[str, Sequence[str], None] = '0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('added', 'imported', 'progressed', 'rated', 'completed', 'dropped', name='kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_activity_media_id_media'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity'))
    )
    op.create_index(op.f('ix_activity_media_id'), 'activity', ['media_id'], unique=False)
    op.create_index('ix_activity_user_id_created_at_id', 'activity', ['user_id', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('contains_spoilers', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_reviews_media_id_media'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('user_id', 'media_id', name=op.f('uq_reviews_user_id_media_id'))
    )
    op.create_index(op.f('ix_reviews_media_id'), 'reviews', ['media_id'], unique=False)
    op.create_table('group_watchlist',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('proposed_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_watchlist_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_group_watchlist_media_id_media'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposed_by'], ['users.id'], name=op.f('fk_group_watchlist_proposed_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_watchlist')),
    sa.UniqueConstraint('group_id', 'media_id', name=op.f('uq_group_watchlist_group_id_media_id'))
    )
    op.create_index(op.f('ix_group_watchlist_media_id'), 'group_watchlist', ['media_id'], unique=False)
    op.create_index(op.f('ix_group_watchlist_proposed_by'), 'group_watchlist', ['proposed_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_watchlist_proposed_by'), table_name='group_watchlist')
    op.drop_index(op.f('ix_group_watchlist_media_id'), table_name='group_watchlist')
    op.drop_table('group_watchlist')
    op.drop_index(op.f('ix_reviews_media_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_activity_user_id_created_at_id', table_name='activity')
    op.drop_index(op.f('ix_activity_media_id'), table_name='activity')
    op.drop_table('activity')
    # ### end Alembic commands ###
