"""retire server push

Episode alerts are scheduled on the phone now, so the server's push system is gone: the threshold
scan's queue (notification_tasks), the device registrations (push_targets) and the per-user switch
(notification_prefs). Their rows are useless without the code that read them, so nothing is kept.
The downgrade recreates the three tables, empty, exactly as 0017 left them.

Revision ID: 0018
Revises: 0017
Create Date: 2026-10-07 20:31:45.044223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0018'
down_revision: Union[str, Sequence[str], None] = '0017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_tasks_media_id'), table_name='notification_tasks')
    op.drop_table('notification_tasks')
    op.drop_index(op.f('ix_push_targets_user_id'), table_name='push_targets')
    op.drop_table('push_targets')
    op.drop_table('notification_prefs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_prefs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('push_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_prefs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_prefs')),
    sa.UniqueConstraint('user_id', name=op.f('uq_notification_prefs_user_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('push_targets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('transport', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('target', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("transport::text = ANY (ARRAY['ntfy'::character varying, 'unifiedpush'::character varying]::text[])", name=op.f('ck_push_targets_transport')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_push_targets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_targets')),
    sa.UniqueConstraint('transport', 'target', name=op.f('uq_push_targets_transport_target'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_push_targets_user_id'), 'push_targets', ['user_id'], unique=False)
    op.create_table('notification_tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('media_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('episode_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('threshold', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('airs_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('next_attempt_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'sent'::character varying, 'failed'::character varying, 'skipped'::character varying, 'expired'::character varying]::text[])", name=op.f('ck_notification_tasks_status')),
    sa.CheckConstraint("threshold::text = ANY (ARRAY['24h'::character varying, 'airing_soon'::character varying]::text[])", name=op.f('ck_notification_tasks_threshold')),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_notification_tasks_media_id_media'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_tasks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_tasks')),
    sa.UniqueConstraint('user_id', 'media_id', 'episode_number', 'threshold', 'airs_on', name=op.f('uq_notification_tasks_dedup'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_notification_tasks_media_id'), 'notification_tasks', ['media_id'], unique=False)
    # ### end Alembic commands ###
